project:
  type: website
  post-render: "R/write_manifest.R"
    

website:
  description: "Diverse waterkwaliteitsanalyses HHSK"
  
  title: "Waterkwaliteitsflitsen"
  navbar:
    logo: logo-hhsk-wit
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HHSK-wkl
format:
  html:
    link-external-newwindow: true
    grid:
      body-width: 900px
    theme:
      light:
        - cosmo
        - brand
      dark:
        - cosmo
        - brand
    css: styles.css

editor: visual

lang: nl

fig-dpi: 150
fig-width: 8
fig-height: 5
knitr:
  opts_chunk:
    dev: "ragg_png"
    
